import { build } from "esbuild";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const result = await build({
	absWorkingDir: root,
	entryPoints: ["claude-mcp.ts"],
	outfile: "dist/claude-mcp.mjs",
	bundle: true,
	platform: "node",
	format: "esm",
	target: "node22",
	minify: true,
	metafile: true,
	legalComments: "none",
	banner: { js: '// Generated by npm run build. Third-party licenses: claude-mcp.LICENSE\nimport { createRequire as __createRequire } from "node:module"; const require = __createRequire(import.meta.url);' },
});

const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
	if (!input.includes("node_modules/")) continue;
	let directory = dirname(resolve(root, input));
	while (directory !== root) {
		try {
			const pkg = JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
			if (pkg.name && pkg.version) { packages.set(directory, pkg); break; }
		} catch (error) {
			if (error.code !== "ENOENT") throw error;
		}
		const parent = dirname(directory);
		if (parent === directory) throw new Error(`No package metadata for ${input}`);
		directory = parent;
	}
}
const notices = [];
for (const [directory, pkg] of [...packages].sort((a, b) => a[1].name.localeCompare(b[1].name))) {
	const licenses = (await readdir(directory)).filter((name) => /^(license|licence|copying)(\.|$)/i.test(name));
	if (!licenses.length) throw new Error(`Missing license for ${pkg.name}`);
	notices.push(`${pkg.name}@${pkg.version}\n${(await Promise.all(licenses.sort().map((name) => readFile(join(directory, name), "utf8")))).join("\n")}`);
}
await writeFile(join(root, "dist/claude-mcp.LICENSE"), notices.join("\n---\n\n"));
